[providers]
dotnet = "8.0"

[phases.build]
cmds = [
  'dotnet restore',
  'dotnet publish -c Release -o out'
]

[start]
cmd = 'dotnet out/ConfirmMe.dll'

[variables]
ASPNETCORE_ENVIRONMENT = 'Production'
ASPNETCORE_URLS = 'http://0.0.0.0:$PORT'
